# Filter by branch, path, tags
name: workflow-1
# on git push this workflow will run
on:
  push:
    branches:
      - main
      - feature/*
      # works -  feature/feat1
      # doesn't work - feature/feat/feature
      # To make above work - feature/**
      - (!feature/feat1) # we don't the workflow to be triggered
    paths:
      - '*.md'
      - '!(images/*)'
      - 'docs/*'
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: step-1-check_os
        run: |
          echo  Repo Name: $GITHUB_REPOSITORY
          echo Event that triggered workflow: $GITHUB_EVENT_NAME
          echo Owner of Repo: $GITHUB_ACTOR
