name: workflow-1
on:
  push:
    branches:
      - main

env:
    workflow_env: 'global env1'
    workflow_env_2: 'global env2'

jobs:
  job-1:
    runs-on: ubuntu-latest
    env:
      - job_env: 'job env1'
      - job_env_2: 'job env2'
    steps:
      - name: step-1
        env:
            step_env: 'step env1'
        run: |
          echo global: ${workflow_env}
          echo global: ${workflow_env_2}
          echo job level: ${job_env}
          echo job level: ${job_env_2}
          echo step level: ${step_env}
          echo commit id: ${GITHUB_SHA}
      - name: step-2
        env:
            step_2_env: 'step 2 env1'
        run: |
          echo global: ${workflow_env}
          echo global: ${workflow_env_2}
          echo job level: ${job_env}
          echo job level: ${job_env_2}
          echo step 1 level: ${step_env}
          echo step 2 level: ${step_2_env}
          echo commit id: ${GITHUB_SHA}
