name: workflow-1
on:
  push:
    branches:
      - master

env:
    - workflow_env: 'global env1'
    - workflow_env_2: 'global env2'

jobs:
  job-1:
    runs-on: ubuntu-latest
    env:
      - job_env: 'job env1'
      - job_env_2: 'job env2'
    steps:
      - name: step-1
        env:
            - step_env: 'step env1'
        run: |
          echo ${workflow_env}
          echo ${workflow_env_2}
          echo ${job_env}
          echo ${job_env_2}
          echo ${step_env}
          echo ${GITHUB_SHA}
